import {
  Search,
  Pencil,
  ArrowLeft,
  Plus,
  Edit,
  Check,
  X,
  ChevronDown,
  ChevronUp,
  User,
  Users,
  Settings,
  Calendar,
  Info,
  AlertTriangle,
  Loader,
  CheckCircle,
  AlertCircle,
  XCircle,
  Eye,
  EyeOff,
  Filter,
  MapPin,
  Circle,
  Trash2Icon,
  Hospital,
  Home,
  Database,
  BookOpen,
  MessageSquare,
  Star,
  CircleDollarSign,
  FileText,
  Upload,
  ArrowDownLeft,
  ArrowUpRight,
  Mail,
  Phone,
  Maximize2,
  GitPullRequest,
  CheckIcon,
} from 'lucide-react';

export const Icons = {
  Search: (props: any) => <Search size={16} {...props} />,
  Pencil: (props: any) => <Pencil size={16} {...props} />,
  ArrowLeft: (props: any) => <ArrowLeft size={16} {...props} />,
  ArrowDownLeft: (props: any) => <ArrowDownLeft size={16} {...props} />,
  ArrowUpRight: (props: any) => <ArrowUpRight size={16} {...props} />,
  Plus: (props: any) => <Plus size={16} {...props} />,
  Edit: (props: any) => <Edit size={16} {...props} />,
  Delete: (props: any) => <Trash2Icon size={16} {...props} />,
  Check: (props: any) => <Check size={16} {...props} />,
  X: (props: any) => <X size={16} {...props} />,
  ChevronDown: (props: any) => <ChevronDown size={16} {...props} />,
  ChevronUp: (props: any) => <ChevronUp size={16} {...props} />,
  User: (props: any) => <User size={16} {...props} />,
  Users: (props: any) => <Users size={16} {...props} />,
  Settings: (props: any) => <Settings size={16} {...props} />,
  Calendar: (props: any) => <Calendar size={16} {...props} />,
  Info: (props: any) => <Info size={16} {...props} />,
  AlertTriangle: (props: any) => <AlertTriangle size={16} {...props} />,
  Loader: (props: any) => <Loader size={16} {...props} />,
  CheckCircle: (props: any) => <CheckCircle size={16} {...props} />,
  AlertCircle: (props: any) => <AlertCircle size={16} {...props} />,
  XCircle: (props: any) => <XCircle size={16} {...props} />,
  Eye: (props: any) => <Eye size={16} {...props} />,
  EyeOff: (props: any) => <EyeOff size={16} {...props} />,
  Filter: (props: any) => <Filter size={16} {...props} />,
  Location: (props: any) => <MapPin size={16} {...props} />,
  Circle: (props: any) => <Circle size={16} {...props} />,
  Hospital: (props: any) => <Hospital size={16} {...props} />,
  Home: (props: any) => <Home size={16} {...props} />,
  Master: (props: any) => <Database size={16} {...props} />,
  Page: (props: any) => <BookOpen size={16} {...props} />,
  MessageSquare: (props: any) => <MessageSquare size={16} {...props} />,
  Star: (props: any) => <Star size={16} {...props} />,
  Dollar: (props: any) => <CircleDollarSign size={16} {...props} />,
  File: (props: any) => <FileText size={16} {...props} />,
  Upload: (props: any) => <Upload size={16} {...props} />,
  Mail: (props: any) => <Mail size={16} {...props} />,
  Phone: (props: any) => <Phone size={16} {...props} />,
  Maximize2: (props: any) => <Maximize2 size={16} {...props} />,
  Request: (props: any) => <GitPullRequest size={16} {...props} />,
  Accept: (props: any) => <CheckIcon size={16} {...props} />,
};
