export const patientsData = [
  {
    id: 'P-1001',
    patientName: 'John Doe',
    patientAvatarUrl: 'https://randomuser.me/api/portraits/men/32.jpg',
    regDateISO: '2024-01-10',
    age: 32,
    gender: 'Male',
  },
  {
    id: 'P-1002',
    patientName: 'Sarah Williams',
    patientAvatarUrl: 'https://randomuser.me/api/portraits/women/44.jpg',
    regDateISO: '2024-02-18',
    age: 27,
    gender: 'Female',
  },
  {
    id: 'P-1003',
    patientName: 'Michael Johnson',
    patientAvatarUrl: 'https://randomuser.me/api/portraits/men/76.jpg',
    regDateISO: '2024-03-05',
    age: 45,
    gender: 'Male',
  },
  {
    id: 'P-1004',
    patientName: 'Emily Brown',
    patientAvatarUrl: 'https://randomuser.me/api/portraits/women/68.jpg',
    regDateISO: '2024-03-22',
    age: 36,
    gender: 'Female',
  },
  {
    id: 'P-1005',
    patientName: 'David Wilson',
    patientAvatarUrl: 'https://randomuser.me/api/portraits/men/15.jpg',
    regDateISO: '2024-04-02',
    age: 52,
    gender: 'Male',
  },
  {
    id: 'P-1006',
    patientName: 'Sophia Martinez',
    patientAvatarUrl: 'https://randomuser.me/api/portraits/women/12.jpg',
    regDateISO: '2024-04-15',
    age: 29,
    gender: 'Female',
  },
];
